# -*- coding: utf-8 -*-
"""flask_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10t5c11mOJrCgieRoTcrJek8-i8EySkwO
"""

import webbrowser
import joblib
from flask import Flask, render_template, request

app = Flask(__name__)

def detection(model, x):
    riesgo = model.predict([x])[0]
    if riesgo == 1:
        riesgo = 'Bajo'
    elif riesgo ==2:
        riesgo = 'Alto'
    return riesgo

@app.route('/', methods=['POST', 'GET'])
def main_app():
    try:
        if request.method == 'POST':
            dia_semana = request.form['dia_semana']
            latitud = request.form['latitud']
            longitud = request.form['longitud']
            mes = request.form['mes']
            hora = request.form['hora']
            minuto = request.form['minuto']
            parametros = (dia_semana, latitud, longitud, mes, hora, minuto)
            lang = detection(model, parametros)
        else:
            lang = None
        return render_template('index.html', result={'riesgo': lang.upper()})
    except:
        return render_template('index.html', result={'riesgo': None})

if __name__ == '__main__':
    model = joblib.load('Modelo/model.pkl')
    app.run(host='127.0.0.1', port=8080, debug=True)



